name: Python 3.8 Workflow
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2

      - name: Zip a folder
        run: |
          zip -r zipado.zip .github/ && ls -la
