name: Python 3.8 Workflow
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - uses: PedroHPAlmeida/terraform-export-envs-action@1.3
        id: Teste
        with:
          tf_variables: '{"chave": "valor"}'
