name: Python 3.8 Workflow
on: [push]

jobs:
    deploy:
      runs-on: ubuntu-latest   
      steps:
        - name: Teste
          uses: PedroHPAlmeida/deploy-docker-render@v0.6
          with:
            render-api-key: ''
            service-id: ''
            image-url: ''
