name: Python 3.8 Workflow
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Test
        id: test
        uses: PedroHPAlmeida/prerequisites-action@v0.4
        with:
          DEFAULT_BRANCH: 'master'
          BRANCHES: 'branch1,branch2,branch3'
