name: Python 3.8 Workflow
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    permissions: write-all
    steps:
      - name: Test
        id: test
        uses: PedroHPAlmeida/prerequisites-action@master
        with:
          DEFAULT_BRANCH: 'master'
          BRANCHES: 'branch1,branch2,branch3'
          PAT_GITHUB: ${{ secrets.PAT_GITHUB_TOKEN }}
