name: Teste
run-name: Teste
on:
  workflow_call:
    inputs:
      input-json:
        type: string
        default: ''

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Exportar variáveis de ambiente
        run: |
          # Converter a string JSON para variáveis de ambiente
          for key in ${{ fromJSON(inputs.input-json) }} | jq -r 'keys[]'); do
            value=${{ fromJSON(inputs.input-json) }} | jq -r ".$key")
            export "$key"="$value"
          done
          # Exibir as variáveis de ambiente exportadas
          env
